# Generated by Django 4.1.3 on 2022-11-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodeltranslation',
            old_name='name',
            new_name='title',
        ),
    ]
