# Generated by Django 4.1.3 on 2022-11-18 12:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_title_productmodeltranslation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodeltranslation',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
