# Generated by Django 4.1.3 on 2022-11-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productmodeltranslation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodeltranslation',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Описание'),
        ),
    ]
